## Jupiter para la visualizacion de las matrices

In [2]:
import numpy as np 
import pandas as pd 
import scanpy as sc

In [23]:
DE_matrix_df=pd.read_csv("../../results/babesia/DE_matrix.tsv", sep="\t",header=0, index_col=0)
pos_gen=pd.read_csv("../../results/babesia/DE_genes_pos.tsv",sep="\t",header=0) 
sig_gen=pd.read_csv("../../results/babesia/significant_DE_genes.tsv",sep="\t",header=0,index_col=0) 
srr_info=pd.read_csv("../../results/babesia/srr_info.tsv",sep="\t",header=0) 
count_table=pd.read_csv("../../results/babesia/SRR9624152.count.txt",sep="\t",header=0)
blast_res=pd.read_csv("/home/hectorjl/WORKING_DIR/biopython/babesia_genomic_analysis/results/blastn/blastn_tab_with_geneid.tab",sep="\t",header=None) 
blast_res.columns=["queryID","subID","pident","unknown","unknown1","unknown2","unknown3","unknown4","eValue","unknown5","NCBI_ID"]
blast_res.drop(["unknown","unknown1","unknown2","unknown3","unknown4","unknown5"], axis=1, inplace=True)

display(DE_matrix_df)
display(pos_gen)
display(sig_gen)
display(srr_info)
display(count_table)
display(blast_res)

          baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
g1     2043.789443       -0.404591  0.209932 -1.927247  0.053949  0.151530
g10      99.915258        1.041434  0.269186  3.868820  0.000109  0.001381
g100    191.095227       -0.138800  0.238022 -0.583139  0.559799  0.726076
g1000   165.822745        0.237591  0.228927  1.037846  0.299342  0.487076
g1001   256.174888        0.018384  0.199664  0.092075  0.926639  0.962096
...            ...             ...       ...       ...       ...       ...
g995    787.895438       -0.132349  0.115995 -1.140984  0.253877  0.442059
g996    255.816738        0.428504  0.165804  2.584409  0.009755  0.044419
g997    241.003020        0.123758  0.181755  0.680903  0.495933  0.673434
g998    244.028333        0.138789  0.180722  0.767966  0.442507  0.629230
g999     39.882092        0.944798  0.424820  2.223996  0.026149  0.089836

[3775 rows x 6 columns]

   geneid DE_status             chr    start      end strand
0     g10        UP  BdivROUEN_Chr1    27676    28449      -
1    g108        UP  BdivROUEN_Chr1   250001   250558      +
2   g1085        UP  BdivROUEN_Chr1  2794840  2795537      +
3   g1139        UP  BdivROUEN_Chr1  2916226  2916726      +
4   g1144        UP  BdivROUEN_Chr1  2926784  2927557      +
..    ...       ...             ...      ...      ...    ...
88   g731        UP  BdivROUEN_Chr1  1925848  1927289      -
89   g824        UP  BdivROUEN_Chr1  2145457  2147055      +
90   g845      DOWN  BdivROUEN_Chr1  2192776  2193459      -
91   g954        UP  BdivROUEN_Chr1  2479353  2479655      +
92   g986        UP  BdivROUEN_Chr1  2580445  2582598      -

[93 rows x 6 columns]

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Expression
g10,99.915258,1.041434,0.269186,3.868820,1.093634e-04,1.380759e-03,UP
g108,103.697683,1.036808,0.312826,3.314332,9.186250e-04,7.378318e-03,UP
g1085,481.976837,1.161471,0.226968,5.117327,3.098958e-07,1.063506e-05,UP
g1139,71.940162,1.163407,0.340930,3.412452,6.438129e-04,5.486216e-03,UP
g1144,192.492429,1.496673,0.321179,4.659934,3.163107e-06,7.462955e-05,UP
...,...,...,...,...,...,...,...
g731,64.705952,1.605439,0.342688,4.684843,2.801750e-06,6.779876e-05,UP
g824,57.339393,1.230951,0.346860,3.548841,3.869300e-04,3.642546e-03,UP
g845,1149.862090,-1.142505,0.129152,-8.846209,9.054293e-19,1.139332e-15,DOWN
g954,583.714582,1.056416,0.213329,4.952051,7.343542e-07,2.148982e-05,UP
g986,73.591746,1.134094,0.323861,3.501793,4.621378e-04,4.183621e-03,UP

,Run,Experiment,Platform,LibraryName,LibraryLayout,Sample,ScientificName,SampleName,Unnamed: 8
0,SRR9624152,SRX6386485,ILLUMINA,ML1,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN
1,SRR9624153,SRX6386484,ILLUMINA,ML2,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN
2,SRR9624154,SRX6386483,ILLUMINA,ML3,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN
3,SRR9624155,SRX6386482,ILLUMINA,PI1,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN
4,SRR9624156,SRX6386481,ILLUMINA,PI2,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN
5,SRR9624157,SRX6386480,ILLUMINA,PI3,PAIRED,SRS5045988,Babesia divergens,Bdivergens_ML_PI_RNAseq,NaN

,BdivROUEN_Chr1,AUGUSTUS,gene,8292,8744,.,+,..1,ID=g1;,1294,453,453.1,1.0000000
0,BdivROUEN_Chr1,AUGUSTUS,gene,9910,10329,.,+,.,ID=g2;,594,420,420,1.000000
1,BdivROUEN_Chr1,GeneMark.hmm3,gene,12369,12767,.,+,.,ID=g3;,52,197,399,0.493734
2,BdivROUEN_Chr1,AUGUSTUS,gene,15693,17643,.,+,.,ID=g4;,131,1893,1951,0.970272
3,BdivROUEN_Chr1,AUGUSTUS,gene,17906,21193,.,+,.,ID=g5;,364,3270,3288,0.994526
4,BdivROUEN_Chr1,GeneMark.hmm3,gene,22689,23748,.,+,.,ID=g6;,280,1045,1060,0.985849
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4072,BdivROUEN_scaff2,GeneMark.hmm3,gene,39293,39799,.,+,.,ID=g4074;,4,271,507,0.534517
4073,BdivROUEN_scaff2,AUGUSTUS,gene,47949,49070,.,+,.,ID=g4075;,0,0,1122,0.000000
4074,BdivROUEN_scaff2,AUGUSTUS,gene,49452,49658,.,-,.,ID=g4076;,0,0,207,0.000000
4075,BdivROUEN_scaff2,GeneMark.hmm3,gene,53456,53776,.,+,.,ID=g4077;,1,101,321,0.314642
4076,BdivROUEN_scaff2,GeneMark.hmm3,gene,61343,61738,.,+,.,ID=g4078;,2,133,396,0.335859

,queryID,subID,pident,eValue,NCBI_ID
0,g2674|BdivROUEN_Chr2|2270658-2273996|strand_-|UP,NC_010575.1_cds_XP_001612125.1_2460,85.663,0.000000e+00,5480381
1,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,85.345,7.520000e-64,5479159
2,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,84.914,3.500000e-62,5479159
3,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,89.560,4.520000e-61,5479159
4,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,87.065,5.850000e-60,5479159
5,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,89.011,2.100000e-59,5479159
6,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261571.1_cds_XP_001610925.1_3321,86.139,3.520000e-57,5479159
7,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261572.1_cds_XP_001609483.1_3888,86.802,9.790000e-58,5477702
8,g3531|BdivROUEN_Chr3|620537-621074|strand_+|UP,NW_026261572.1_cds_XP_001609483.1_3888,85.787,2.120000e-54,5477702

In [29]:
anotated_genes=["g2674", "g3531"] 

for gene in anotated_genes: 
    display(sig_gen.loc[gene,"log2FoldChange"])

KeyError: 'g2674'